GLOBAL_LIST_INIT(global_quest_types, list(
	QUEST_DIFFICULTY_EASY = list(QUEST_RETRIEVAL, QUEST_COURIER, QUEST_KILL),
	QUEST_DIFFICULTY_MEDIUM = list(QUEST_CLEAR_OUT),
	QUEST_DIFFICULTY_HARD = list(QUEST_OUTLAW),
))
